language: go
go: 1.x

branches:
  only:
    - master
    - develop

env:
  - GO111MODULE=on

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  # Lint stuff
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.3
  # Dep
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  

install:
  - dep ensure -v --vendor-only
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

before_script:
  - golangci-lint run -v --issues-exit-code=0 --disable-all -E=govet -E=errcheck -E=staticcheck -E=unused -E=gosimple -E=structcheck -E=varcheck -E=ineffassign -E=deadcode -E=typecheck -E=lll -E=gosec ./...

script:
  - ginkgo -r --failOnPending --cover --trace ./...

after_success:
  - gover
  - goveralls -coverprofile=gover.coverprofile -service travis-ci -repotoken $COVERALLS_TOKEN
