[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/daihasso/slogging"
  version = ">=0.1.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "~1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.4.1"

[prune]
  go-tests = true
  unused-packages = true
